# Generated by Django 2.2.3 on 2019-07-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATA', '0002_auto_20190722_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matapelajaran',
            name='jadwal_berakhir',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='jadwal_dimulai',
            field=models.DateTimeField(),
        ),
    ]
