# Generated by Django 2.2.3 on 2019-07-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATA', '0003_auto_20190722_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='banyak_soal',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='bobot_nilai',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='livecode',
            name='banyak_soal',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='livecode',
            name='bobot_nilai',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='nomor_absen',
            field=models.SmallIntegerField(),
        ),
    ]
