# Generated by Django 2.2.3 on 2019-07-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebun_binatang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hewan',
            name='berat',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hewan',
            name='umur',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kandang',
            name='luas_kandang',
            field=models.PositiveIntegerField(),
        ),
    ]
