# Generated by Django 2.2.3 on 2019-07-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0002_auto_20190722_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='bidang',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dokter',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='obat',
            name='kandungan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='obat',
            name='khasiat',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='obat',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='alamat',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='keluhan',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resep',
            name='kumpulan_obat',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resep',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
